name: cppcheck-action
on : [push]
defaults:
  jobs :
   build :
    name : cppcheck
    runs-on : ubuntu-latest
    steps :
      -uses : actions/checkout@v2
       run : sudo apt-get -y install cppcheck
       - name: cppcheck code
         run : cppcheck
  
